# 注册中心的信息
server:
  port: 8070
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    gateway:
      routes:
        - id: article_route
          uri: http://127.0.0.1:9081
          predicates:
            - Path=/api/**